# Generated by Django 5.2.3 on 2025-06-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
